export const TOPIC_FCM = 'TOPIC_FCM';

export const CMD_SEND_DEVICE = 'CMD_SEND_DEVICE';
export const CMD_SEND_TOPIC = 'CMD_SEND_TOPIC';
export const CMD_SEND_GROUP = 'CMD_SEND_GROUP';

export const CMD_SUBSCRIBE = 'CMD_SUBSCRIBE';
export const CMD_UNSUBSCRIBE = 'CMD_UNSUBSCRIBE';
